---
sudo: required
language: node_js
node_js:
  - node
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
jobs:
  include:
    - stage: Build images
      name: ci
      script: ./scripts/docker-build ci
    - stage: Build images
      name: serve
      script: ./scripts/docker-build serve
