---
sudo: required

language: node_js
node_js:
  - node

services:
  - docker

before_install:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

stages:
  - Build images
  - Create release

jobs:
  include:
    - stage: Build images
      name: ci
      script: ./scripts/docker-build ci
    - stage: Build images
      name: serve
      script: ./scripts/docker-build serve
    - stage: Build images
      name: laravel
      script: ./scripts/docker-build laravel
    - stage: Create release
      name: semantic-release
      script: npx semantic-release
      if: branch = master
