---
sudo: required

language: node_js
node_js:
  - node

services:
  - docker

before_install:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: Build images
      name: ci
      script: ./scripts/docker-build ci
    - stage: Build images
      name: serve
      script: ./scripts/docker-build serve
    - stage: Build images
      name: laravel
      script: ./scripts/docker-build laravel

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
  on:
    branch: master
    node: lts/*
